name: Forward Telegram Messages

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  forward_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4

      - name: Forward messages
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_TARGET_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - <<EOF
          import requests
          from bs4 import BeautifulSoup

          # URL of the public Telegram channel
          telegram_channel_url = 'https://t.me/s/Rasoolkgfx_3'

          # Fetch the latest messages from the public URL
          response = requests.get(telegram_channel_url)
          soup = BeautifulSoup(response.text, 'html.parser')

          # Extract the latest message (assuming it's the last <div> with class "tgme_widget_message_text")
          latest_message = soup.find_all('div', class_='tgme_widget_message_text')[-1].get_text(strip=True)

          # Send the message to the target Telegram channel
          bot_token = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          chat_id = '${{ secrets.TELEGRAM_TARGET_CHAT_ID }}'
          send_message_url = f'https://api.telegram.org/bot{bot_token}/sendMessage'

          response = requests.post(send_message_url, data={'chat_id': chat_id, 'text': latest_message})
          if response.status_code != 200:
              print(f'Failed to send message: {response.text}')
          else:
              print('Message sent successfully')
          EOF
