name: Notify New Followers

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the notification script
      env:
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        TWITTER_CONFIRMATION_CODE: ${{ secrets.TWITTER_CONFIRMATION_CODE }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python script.py
